config/routes.rb
Rails.application.routes.draw do
  root :to => 'stories#index'

  resources :stories do
    resources :additions
  end

  resources :additions do
    resources :images
  end
end

app/models/addition.rb
class Addition < ActiveRecord::Base
  belongs_to :story
  belongs_to :image
  validates :body, :presence => true
  validates :author, :presence => true
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :additions
  validates :name, :presence => true
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :additions
  validates :title, :presence => true
  validates :body, :presence => true
  validates :creator, :presence => true
end

app/controllers/additions_controller.rb
class AdditionsController < ApplicationController
  def new
    @story = Story.find(params[:story_id])
    @addition = @story.additions.new

    images = Image.all
    image_count = images.length
    selected_id = 1 + rand(image_count).ceil
    @image = Image.find(selected_id)
    if @story.additions.length > 1
      @placeholder = @story.additions[-2].body
    else
      @placeholder = @story.body
    end
  end

  def create
    @story = Story.find(params[:story_id])
    @image = Image.find(addition_params[:image_id])
    @addition = @story.additions.new(addition_params)
    if @addition.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def edit
    @addition = Addition.find(params[:id])
    render :edit
  end

  def update
    @addition = Addition.find(params[:id])
    @story = Story.find(@addition.story_id)
    if @addition.update(addition_params)
      redirect_to story_path(@addition.story)
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:story_id])
    @addition = Addition.find(params[:id])
    @addition.destroy
    redirect_to story_path(@story)
  end

  private
  def addition_params
    params.require(:addition).permit(:body, :author, :image_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to stories_path
    else
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
    render :edit
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to story_path(@story)
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  private
  def story_params
    params.require(:story).permit(:title, :body, :creator)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/additions/edit.html.erb
<h1>Edit your contribution</h1>

<%= form_for [@story, @addition] do |f| %>
  <div class="form-group">
    <%= f.label :body, "Keep it to one sentence!" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author, "Your Name" %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default center-block" %>
<% end %>

<%= link_to "Back", :back %>

app/views/additions/new.html.erb
<div class="jumbotron">
  <h1>New Addition to <b><%= @story.title %></b></h1>

  <%= render "layouts/errors", :object => @addition %>

  <p class="text-center"><%= image_tag("halloween/#{@image.name}.svg", size: "666") %></p>

  <p>
    Using the image above as inspiration, generate an addition to the story!
  </p>

  <%= form_for [@story, @addition] do |f| %>
    <div class="form-group">
      <%= f.label :body, "Make Your Addition (only one sentence!)" %>
      <%= f.text_area :body, class: "form-control", placeholder: "Previous sentence: #{@placeholder}" %>
    </div>
    <div class="form-group">
      <%= f.label :author, "Your Name" %>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <%= f.hidden_field :image_id, :value => @image.id %>
    <%= f.submit "Submit", class: "btn btn-default center-block" %>
  <% end %>

  <%= link_to "Back", :back %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Fix your errors, before the Boogey Man gets you!</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Scarrrry StoryTyme</a>
    </div>
    <ul class="nav navbar-nav pull-right">
      <li><a href="/stories/new">Add a New Story</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scary StoryTyme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Starter sentence for your story" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :creator, "Your Name" %>
    <%= f.text_field :creator, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default center-block" %>
<% end %>

app/views/stories/edit.html.erb
<h1>Edit <%= @story.title %></h1>

<%= render "form" %>

<%= link_to "Back", :back %>

app/views/stories/index.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h1 class="text-center">Scarrrry StoryTyme</h1>
  </div>
  <div class="panel-body">
    <h4 class="text-center">Active Stories</h4>
  </div>
  <ul class="list-group">
    <% @stories.order(created_at: :desc).each do |story| %>
    <li class="list-group-item"><%= link_to story.title, story_path(story) %> (<%= story.additions.length %> contributions)</li>
    <% end %>
  </ul>
</div>

app/views/stories/new.html.erb
<div class="jumbotron">
  <h1>New Story</h1>

  <%= render "layouts/errors", :object => @story %>

  <%= render "form" %>
</div>

app/views/stories/show.html.erb
<div class="jumbotron">
  <h1><%= @story.title %><small> started by <%= @story.creator %></h1>
  <p>
    <%= @story.body %>
    <% @story.additions.each do |addition| %>
      <%= addition.body %>
    <% end %>
  </p>
  <p class=pull-right><%= link_to "Edit", edit_story_path(@story) %> | <%= link_to "Delete", story_path(@story),
                                                                                    :data => {:confirm => "Are u sure?",
                                                                                              :method => "delete"} %></p>
</div>

<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Story History:</h3>
  </div>
  <div class="panel-body">
    <h4 class="text-center"><%= @story.body %> (from <%= @story.creator %>)</h4>
  </div>
  <ul class="list-group">
    <% @story.additions.each do |addition| %>
      <li class="list-group-item clearfix">
        <%= image_tag("halloween/#{addition.image.name}.svg", size: "37") %>
        <h4 class="pull-right clearfix" style="padding: -37px 0px 0px 66px"><%= addition.body %> (from <%= addition.author %>)</h4>
        <%= link_to "Edit Contribution", edit_addition_path(addition) %> |
        <%= link_to "Delete Contribution", story_addition_path(@story, addition), :data => {:confirm => "Are u sure?", :method => "delete"} %>
      </li>
    <% end %>
  </ul>
</div>
<button class="btn btn-danger btn-lg pull-right"><%= link_to "Add to this story!", new_story_addition_path(@story), {:style=>'color:white;'}%></button>